name: Build linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          # optional parameters follow
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - run: flutter --version
      - run: apt update && apt install ninja
      - run: flutter build linux
      
      - name: Commit files
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf shock_alarm.tar.gz *
          cd ../../../../../
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShockAlarm-Android
          path: build/linux/x64/release/bundle/shock_alarm.tar.gz