name: Build android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          ls -la ./
          ls -la ./battery_optimization_helper/
      - run: ./flutter/bin/flutter doctor
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/android.keystore
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> android/key.properties
          echo "storeFile=../android.keystore" >> android/key.properties
      - run: ./flutter/bin/flutter build apk
      - name: Rename apk
        id: rename_apk
        run: |
          apkName="ShockAlarm.apk"
          echo "apkName=$apkName" >> $GITHUB_OUTPUT

          mkdir -p output
          mv build/app/outputs/flutter-apk/app-release.apk output/$apkName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShockAlarm-Android
          path: output/${{ steps.rename_apk.outputs.apkName }}